cmake_minimum_required(VERSION 3.19)

set(craftworld_known_comps static shared)
set(craftworld_comp_static NO)
set(craftworld_comp_shared NO)
foreach (craftworld_comp IN LISTS ${CMAKE_FIND_PACKAGE_NAME}_FIND_COMPONENTS)
    if (craftworld_comp IN_LIST craftworld_known_comps)
        set(craftworld_comp_${craftworld_comp} YES)
    else ()
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "craftworld does not recognize component `${craftworld_comp}`.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
endforeach ()

if (craftworld_comp_static AND craftworld_comp_shared)
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
        "craftworld `static` and `shared` components are mutually exclusive.")
    set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
    return()
endif ()

set(craftworld_static_targets "${CMAKE_CURRENT_LIST_DIR}/craftworld-static-targets.cmake")
set(craftworld_shared_targets "${CMAKE_CURRENT_LIST_DIR}/craftworld-shared-targets.cmake")

macro(craftworld_load_targets type)
    if (NOT EXISTS "${craftworld_${type}_targets}")
        set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE
            "craftworld `${type}` libraries were requested but not found.")
        set(${CMAKE_FIND_PACKAGE_NAME}_FOUND FALSE)
        return()
    endif ()
    include("${craftworld_${type}_targets}")
endmacro()

if (craftworld_comp_static)
    craftworld_load_targets(static)
elseif (craftworld_comp_shared)
    craftworld_load_targets(shared)
elseif (DEFINED craftworld_SHARED_LIBS AND craftworld_SHARED_LIBS)
    craftworld_load_targets(shared)
elseif (DEFINED craftworld_SHARED_LIBS AND NOT craftworld_SHARED_LIBS)
    craftworld_load_targets(static)
elseif (BUILD_SHARED_LIBS)
    if (EXISTS "${craftworld_shared_targets}")
        craftworld_load_targets(shared)
    else ()
        craftworld_load_targets(static)
    endif ()
else ()
    if (EXISTS "${craftworld_static_targets}")
        craftworld_load_targets(static)
    else ()
        craftworld_load_targets(shared)
    endif ()
endif ()
